DEV-309 Set access_token from assessment_plan_url
credo-ai/credoai_connect pull request #33
Opened 2023-02-24 00:38 UTC by aproxacs

## Change description
Vendor portal users do not use API key. Instead, `assessment_plan_url` they get includes `access_token`. To support this, if the `access_token` is included in the `assessment_plan_url`, sets' client's `access_token` and `api_base` with it.

2023-03-06 16:34 UTC, credo-nate requested changes

2023-03-06 16:34 UTC, credo-nate commented on connect/governance/credo_api_client.py
> +            # self.logger.error("Path to config file Not Found")
Why is this commented out?

2023-03-06 16:34 UTC, credo-nate commented on connect/governance/governance.py
> +        return api_base, query.get("access_token", [None])[0]
Access token in a GET parameter is a security issue unless this is a one time token and/or has a short lifetime.

2023-03-07 09:54 UTC, aproxacs commented
Closing this PR, since we decided not to use access_token in the assessment_plan_url. 
Instead use API key : related PR : https://github.com/credo-ai/vendor-portal/pull/13

2023-03-07 09:54 UTC, closed without merging